import React, { useEffect, useState } from 'react';
import {
    View,
    StyleSheet,
    Image,
    ActivityIndicator,
    FlatList,
    SafeAreaView
} from 'react-native';
import DetailsHeader from '../components/DetailsHeader';
import {
    hp,
    responsiveImageSize,
    rfpercentage,
    wp,
} from '../utils/responsive';
import { COLORS, FONTS, FONTWEIGHT, colors } from '../utils/constants';
import termsService from '../services/termsService';
import { List } from 'react-native-paper';
import FooterLogo from '../components/FooterLogo';



const avator = responsiveImageSize(320, 400);



const termsCondition = [
    {
        "id": 1,
        "description": "This electronic document is the terms and conditions for access to or usage of .In Website, is based on the applicable rules and regulations in terms of information technology act, 2000 (“it act, 2000”) and in accordance with the provisions of rule 3 (1) of the information technology (intermediaries guidelines) rules, 2011."
    },
    {
        "id": 2,
        "description": "This electronic record is generated by a computer system and does not require any physical or digital signatures."
    },
    {
        "id": 3,
        "description": "The domain name padmavathy jewellers.com, including the related mobile site and mobile application as well as the portal .Com (hereinafter referred to as “platform”) is owned and operated by PADMAVATHY JEWELLERS, 470, The Chola Tower, Trichy Rd,opp. Ambal Theatre, Singanallur, Coimbatore - 641041. Time: mon - sun (9:00 – 18:00)."
    },
    {
        "id": 4,
        "description": "Hereinafter, the word ‘user’ shall collectively imply a .In, a buyer, and any visitor on the platform, to you refers to terms of use, ‘you’ and ‘your’ shall relate to any natural or legal person who has agreed to become a buyer on the platform by providing registration data while registering on the platform using computer systems. The word and the terms ‘we’, ‘us’ and ‘our’ shall mean padmavathy jewellers.com"
    },
    {
        "id": 5,
        "description": "By mere use of this platform, you shall be contracting with padmavathy jewellers.com, and these terms and conditions including the policies constitute your binding obligations to padmavathy jewellers.com"
    },
    {
        "id": 6,
        "description": "We reserve the right, at our sole discretion, to change, modify, add, or remove portions of the to you at any time. Your continued use of the platform following the changes or updates will mean that you accept and agree to the revisions. As long as you comply with the to you, we grant you a personal, non-exclusive, non-transferable, and limited privilege to enter and use the platform."
    },
    {
        "id": 7,
        "description": "Only persons eligible form a legally binding contracts under indian contract act, 1872 are eligible for membership. Incompetent persons cannot enter into a contract. As a minor if youwish to use or transact on website, such use or transaction may be made by your legal guardian or parents on the website. padmavathy jewellers.com reserves the right to terminate your membership and / or refuse to provide you with access to the website if it is brought to padmavathy jewellers.com's notice or if it is discovered that you are incompetent to contract."
    },
    {
        "id": 8,
        "description": "If you register, you shall be responsible for all activities that occur under your display name and password. You agree that if you provide any incorrect information of any type, we shall have the right to indefinitely suspend or terminate or block access of your membership on the website and refuse to provide you with access to the website."
    },
    {
        "id": 9,
        "description": "You agree that communications is only through electronic media."
    },
    {
        "id": 10,
        "description": "padmavathy jewellers.com provides the products as detailed in the specifications listed against each product. Any mismatches with regard to the quality, purity as the case may be, shall be brought to the immediate attention of padmavathy jewellers.com where there is genuine product errors, padmavathy jewellers.com shall take the responsibility. However, such a facility is not available when the product is not properly and delicately handled by you as required in each specific case."
    },
    {
        "id": 11,
        "description": "Membership is free for buyers through this website padmavathy jewellers.com does not charge any fee for browsing and buying on the website. However, padmavathy jewellers.com has a right to charge any fee for whole or partial use of the website, if need be."
    },
    {
        "id": 12,
        "description": "You agree, undertake and confirm that your use of website shall be strictly governed by the following binding principles:\n- You shall not host, display, upload, modify, publish, transmit, update or share any information which:\n  - Belongs to another person and to which you does not have any right to not allowed by indian law and /or under any acts in india.\n  - Is misleading in any way\n- You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the website or any transaction being conducted on the website, or with any other person's use of the website."
    },
    {
        "id": 13,
        "description": "Our current privacy policy is available at / s /privacy policy. If you object to your information being transferred or used in this way please do not use website."
    },
    {
        "id": 14,
        "description": "We and our affiliates will share / sell / transfer / license / covey some or all of your personal"
    },
    {
        "id": 15,
        "description": "In this website, all the materials and products contain specifications as given against each product. All these products require delicate handling and any breakages due to any reasons are not at the fault of padmavathy jewellers.com only purity in terms of gold and silver will be entertained for replacement, if any."
    },
    {
        "id": 16,
        "description": "While availing any of the payment method/s available on the website, we will not be responsible or assume any liability, what so ever in respect of any loss or damage rising directly or indirectly to you due to:\n- Lack of authorization for any transaction/s, or\n- Exceeding the preset limit mutually agreed by you and between\"bank/s\", or\n- Any payment issues arising out of the transaction, or\n- Decline of transaction for any other reason/s"
    },
    {
        "id": 17,
        "description": "All payments made against the purchases / services on website by you shall be compulsorily in indian rupees acceptable in the republic of india. Website will not facilitate transaction with respect to any other form of currency with respect to the purchases made on website."
    },
    {
        "id": 18,
        "description": "Before shipping / delivering your order to you, padmavathy jewellers.com may request you to provide supporting documents (including but not limited to govt. Issued id and address proof) to establish the ownership of the payment instrument used by you foryour purchase. This is done in the interest of providing a safe online shopping environment to our users."
    },
    {
        "id": 19,
        "description": "You, as a buyer, understand that upon initiating a transaction you are entering into a legally binding and enforceable contract with the .In To purchase the products and /or services from the padmavathy jewellers.com using the payment facility, and you shall pay the transaction price through your issuing bank to the padmavathy jewellers.com using payment facility."
    },
    {
        "id": 20,
        "description": "Except for cash on delivery transaction, refund, if any, shall be made at the same issuing bank from where transaction price was received."
    },
    {
        "id": 21,
        "description": "For cash on delivery transactions, refunds, if any, will be made via demand draft in favour of the buyer (as per registration details provided by the buyer)"
    },
    {
        "id": 22,
        "description": "Refund shall be made in indian rupees only and shall be equivalent to the transaction price received in indian rupees."
    },
    {
        "id": 23,
        "description": "Replacements are done only based on transaction to transaction basis. Under no circumstances, money will be refunded."
    },
    {
        "id": 24,
        "description": "Jurisdiction is only at coimbatore, tamilnadu, india. padmavathy jewellers.com we do not warrant that product description or other content of this website is accurate, complete, reliable, current, or error-free and assumes no liability in this regard."
    },
    {
        "id": 25,
        "description": "In no event shall padmavathy jewellers.com be liable for any special, incidental,indirect or consequential damages of any kind in connection with these terms of use, even if user has been informed in advance of the possibility of such damages."
    },
    {
        "id": 26,
        "description": "Please contact usfor any questions or comments (including all inquiries unrelated tocopyright infringement) regarding this website Grievance officer In accordance with information technology act 2000 and rules made there under,the name and contact details of the grievance officer are provided below:"
    },
    {
        "id": 27,
        "description": "PADMAVATHY JEWELLERS \n470, The Chola Tower, \nTrichy Rd,opp. \nAmbal Theatre, Singanallur, \nCoimbatore - 641041.\nTime: mon - sun (9:00 – 18:00)"
    },
    {
        "id": 28,
        "description": "If padmavathy jewellers.com has suspicion or knowledge, that any of its buyers and padmavathy jewellers.com ’s are involved in any activity that is intended to provide claims or information thatis false, misleading or not genuine, then padmavathy jewellers.com may while reserving its rights to initiate civil and/or criminal proceedings against user may also at its solediscretion suspend, block, restrict, cancel the display name of such buyer and padmavathy jewellers.com and /or disqualify that user and any related users from availing protection through this program."
    },
    {
        "id": 29,
        "description": "padmavathy jewellers.com reserves its right to initiate civil and / or criminal proceedings against user who, files a invalid and / or false claims or provides false, incomplete, or misleading information. In addition to the legal proceedings as for said,.In May at its sole discretion suspend, block, restrict, cancel the display name [and its related display names] of such user and / or disqualify that user and any related users from availing protection through this program. Any person who, knowingly and with intent to injure, defraud or deceive, files a fraudulent complaint containing false, incomplete, or misleading information may be guilty of a criminal offence and will be prosecuted to the fullest extent of the law."
    },
    {
        "id": 30,
        "description": "For more details related to replacement policy, refer to /help/cancellation-returns."
    }
]



const ListItem = ({ index, item, description }) => (
    <View style={{ marginTop: hp(1) }}>
        <List.Item
            title={`${index + 1}. ${description}`}
            titleNumberOfLines={10}
            style={styles.listItem}
            titleStyle={styles.copytxt}
        />
    </View>
);


const TermConditions = ({ navigation }) => {

    // const [termsCondition, setTermsCondition] = useState('');
    const [image, setImage] = useState('');
    const [imageLoading, setImageLoading] = useState(true);


    const getTermsCondition = async () => {
        const payload = { type: 2 }
        try {
            const response = await termsService.getAllTermsCondition(payload);
            const img = response.urlpath + response.image;
            setImage(img)
            // setTermsCondition(response.list)
        } catch {
            console.log("error terms condition");
        }
    }

    useEffect(() => {
        getTermsCondition()
    }, [])


    const renderImage = () => {
        if (image) {
            return (
                <Image
                    source={{ uri: image }}
                    style={styles.imageStyle}
                    onLoadStart={() => setImageLoading(true)}
                    onLoad={() => setImageLoading(false)}
                    onError={(error) => {
                        setImageLoading(false);
                    }}
                />
            );
        } else {
            return (
                <ActivityIndicator size="large" color={colors.gradientBg} />
            );
        }
    };



    return (
        <SafeAreaView style={styles.container}>

            <FlatList
                data={termsCondition}
                style={{marginBottom:hp('6%')}}
                keyExtractor={(item, index) => index.toString()}
                renderItem={({ item, index }) => <ListItem {...item} index={index} />}
                ListHeaderComponent={
                    <View>
                        <DetailsHeader
                            title="Terms and Conditions"
                            onBackPress={() => navigation.goBack()}
                            onNotifyPress={() => {
                                navigation.navigate('Notification');
                            }}
                            onWishlistPress={() => {
                                navigation.navigate('WishList');
                            }}
                        />
                        <View style={{ marginTop: hp(2) }}>
                            {renderImage()}
                        </View>
                    </View>}
            />
              
              <FooterLogo />

        </SafeAreaView>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor:COLORS.WHITE,
    },
    imageStyle: {
        width:wp('90%'),
        height:hp('45%'),
        borderRadius: 8,
        overflow: 'hidden',
        alignSelf: 'center'
    },
    titleStyle: {
        fontFamily: FONTS.OUTFIT_MEDIUM,
        fontSize: rfpercentage(2),
        width: hp(38),
        fontWeight:FONTWEIGHT.NORMAL,
        color: COLORS.DARK_PRIMARY,
        paddingLeft: 20,
        paddingRight: 20,
    },
    cardContainer: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    copyContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingLeft: 20,
        paddingRight: 20,
    },
    copytxt: {
        fontFamily: FONTS.OUTFIT_MEDIUM,
        fontSize: rfpercentage(2),
        fontWeight:FONTWEIGHT.NORMAL,
        color: '#878787',
        textAlign: 'justify'
    },
    desContainer: {
        padding: 16,
        marginBottom: hp(10)
    },
    listItem: {
        borderBottomWidth: 1,
        borderBottomColor: '#ddd'
    },
    poweredByLogo: {
        width: 45,
        height: 25,
        resizeMode: 'contain'
    },
});

export default TermConditions;
