export const strings = {
    welcomeMessage: 'Welcome to My App',
    homeScreen: {
      title: 'Home',
      description: 'Explore and enjoy our app!',
      buttonText: 'Go to Details',
    },
    detailsScreen: {
      title: 'Details',
      content: 'This is the details screen.',
      backButton: 'Go Back',
    },
    loginScreen: {
      title: 'Login',
      subTitle:'Lorem Ipsum is simply dummy text of the printing and typesetting',
      usernamePlaceholder: 'Username',
      mobilePlaceholder:'Mobile',
      passwordPlaceholder: 'Password',
      loginButton: 'Log In',
      forgotPassword: 'Forgot Password?',
      newUser:'Don’t have a account?',
      createAccount:'Register Now',
      register: 'Register',
      keepMeLogin:'Remember Me',
      loginFailed:'Login Failed',
      skipLogin: 'Skip',
      branch:'Branch',
      selectBranch:'Select Branch'
    },
    registerScreen: {
      title: 'Register Here !',
      fullNamePlaceholder: 'First Name',
      lastNamePlaceholder: 'Last Name',
      emailPlaceholder: 'Email',
      mobilePlaceholder:'Mobile',
      additionalMobile:'Additional Mobile Number',
      addressPlaceholder:'Address',
      dobPlaceholder:'Date Of birth',
      genderPlaceholder:'Gender',
      countryPlaceeholder:'Country',
      statePlaceholder:'State',
      cityPlaceholder:'City',
      pincodePlaceholder:'Pincode',
      passwordPlaceholder: 'Password',
      confirmPasswordPlaceholder: 'Confirm Password',
      branch:'Branch',
      selectBranch:'Select Branch',
      registerButton: 'Create Account',
      backtologin:'Already have an account?',
      clickhere:'Login',
      termsCondition :'By clicking here, I state that I have read and understood the',
      termsCondition2 : 'terms and conditions'
    },
    forgotScreen: {
      title: 'Forgot Password',
      mobileNo:'Mobile Number',
      subTitle:'Lorem Ipsum is simply dummy text of the printing and typesetting',
      mobilePlaceholder:'Enter Your Mobile Number',
      resetPassword: 'Reset Password',
      forgotFailed:'Forgot Failed',
      unexpectedError:'An unexpected error occurred. Please try again.'
    },
    verifyOtpScreen: {
      title: 'Verify OTP',
      enter:'Enter 4 digit verification code send to your number',
      resend:'Resend code in',
      subTitle:'Lorem Ipsum is simply dummy text of the printing and typesetting',
      backtologin:'Back to Login ?',
      clickhere:'Click Here',
      submit: 'Submit',
    },
    resetPasswordScreen: {
      title: 'Change Password',
      mobileNo:'Mobile Number',
      subTitle:'Lorem Ipsum is simply dummy text of the printing and typesetting',
      mobilePlaceholder:'Enter Your Mobile Number',
      password: 'Reset Password',
      passwordPlaceholder:'Enter your password',
      newPassword:'New Password',
      newPasswordPlaceholder:'New Password',
      rePassword:'Confirm Password',
      rePasswordPlaceholder:'Confirm password',
      forgotFailed:'Forgot Failed',
      unexpectedError:'An unexpected error occurred. Please try again.'
    },

    // Add more strings as needed
  };
  
  